#!/bin/sh
# {{@@ header() @@}}

# START defaults
user_resources=$HOME/.Xresources
user_modmap=$HOME/.Xmodmap
sys_resources=/etc/X11/xinit/.Xresources
sys_modmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sys_resources ]; then
	xrdb -merge $sys_resources
fi

if [ -f $sys_modmap ]; then
	xmodmap $sys_modmap
fi

if [ -f "$user_resources" ]; then
	xrdb -merge "$user_resources"
fi

if [ -f "$user_modmap" ]; then
	xmodmap "$user_modmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi
# END defaults

session=${1:-gnome}

export WM="$session"

case $session in
gnome)
	export XDG_SESSION_TYPE=x11
	export GDK_BACKEND=x11
	exec gnome-session
	;;
budgie)
	export XDG_CURRENT_DESKTOP=Budgie:GNOME
	exec budgie-desktop
	;;
i3)
	exec i3
	;;
*)
	exec "$1"
	;;
esac
