#!/bin/sh

export QT_QPA_PLATFORMTHEME=gtk2
export npm_config_prefix=~/.node_modules

PATH="$HOME/.node_modules/bin:$PATH"
PATH="$HOME/.yarn/bin:$PATH"
PATH="$PATH:$HOME/bin"
PATH="$PATH:$HOME/go/bin"

# set ruby path
if hash ruby 2>/dev/null; then
	PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
	gem_home=$(ruby -e 'print Gem.user_dir')
	export GEM_HOME=$gem_home
fi
