#!/bin/sh
# {{@@ header() @@}}

export VISUAL=nvim
export EDITOR=nvim

# add local bin files to path
PATH="$PATH:$HOME/bin"

# {%@@ if exists('$HOME/.asdf/asdf.sh') @@%}
# source asdf
. $HOME/.asdf/asdf.sh
# {%@@ endif @@%}

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# {%@@ if exists_in_path('pip') or exists_in_path('pip3') @@%}
# bin path for pip
PATH="$PATH:$HOME/.local/bin"
# {%@@ endif @@%}

# {%@@ if exists_in_path('npm') @@%}
# add bin files installed by npm to path
export npm_config_prefix=~/.node_modules
PATH="$HOME/.node_modules/bin:$PATH"
# {%@@ endif @@%}

# {%@@ if exists_in_path('yarn') @@%}
# add bin files installed by yarn to path
PATH="$HOME/.yarn/bin:$PATH"
# {%@@ endif @@%}

# {%@@ if exists_in_path('ruby') @@%}
# set add bin files installed by gem to path
PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
gem_home=$(ruby -e 'print Gem.user_dir')
export GEM_HOME=$gem_home
# {%@@ endif @@%}
