#!/bin/bash

# not running interactively then bail
[[ $- != *i* ]] && return

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    source ~/.zplug/init.zsh && zplug update
else
    source ~/.zplug/init.zsh
fi

# zplug plugins
zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug "yous/vanilli.sh"
zplug "mafredri/zsh-async"
zplug "supercrabtree/k"
zplug "zsh-users/zsh-autosuggestions"
zplug "sindresorhus/pure", use:pure.zsh, as:theme

# install missing plugins
zplug check || zplug install

# Then, source plugins and add commands to $PATH
zplug load

# set nvim
export VISUAL=nvim
export EDITOR=nvim

# Get wal colours
(cat ~/.cache/wal/sequences &)

# aliases
alias vim='nvim'
alias vi='nvim'
alias dotdrop='dotdrop --cfg=~/dotfiles/config.yaml'
alias mirrors='sudo reflector --score 100 --fastest 25 --sort rate --save /etc/pacman.d/mirrorlist --verbose'

