#!/bin/zsh
# {{@@ header() @@}}

# not running interactively then bail
[[ $- != *i* ]] && return

# Zinit installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-bin-gem-node

# End of Zinit's installer chunk

# Zinit commands

zinit light yous/vanilli.sh

# shell bin files
zinit wait"1" lucid from"gh-r" as"null" for \
    sbin"fzf"               junegunn/fzf-bin \
    sbin"lazydocker"        jesseduffield/lazydocker \
    sbin"**/fd"             @sharkdp/fd \
    sbin"**/bat"            @sharkdp/bat \
    sbin"**/pastel"         @sharkdp/pastel \
    sbin"exa* -> exa"       ogham/exa \
    sbin"**/delta"          dandavison/delta \
    sbin"zoxide* -> zoxide" ajeetdsouza/zoxide \
    sbin"tldr* -> tldr"     dbrgn/tealdeer

zplugin ice as"null" from"gh-r" bpick"*linux_x86_64*" sbin"duf"
zplugin light muesli/duf

zinit ice as"program" pick"yank" make
zinit light mptre/yank

zplugin ice wait'1' lucid
zplugin light laggardkernel/zsh-thefuck

zinit ice wait lucid
zinit load 'wfxr/forgit'

zinit sbin make light-mode for dylanaraps/fff

zinit pick"misc/quitcd/quitcd.bash_zsh" sbin make light-mode for jarun/nnn

# zsh scripts
zinit wait lucid for \
    zdharma/history-search-multi-word \
    atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
        zdharma/fast-syntax-highlighting \
    blockf \
        zsh-users/zsh-completions \
    atload"!_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions

zinit ice wait"0c" lucid reset \
    atclone"local P=${${(M)OSTYPE:#*darwin*}:+g}
            \${P}sed -i \
            '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
            \${P}dircolors -b LS_COLORS > c.zsh" \
    atpull'%atclone' pick"c.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS

# prompt
zinit ice wait'!' lucid atload'source ~/.p10k.zsh; _p9k_precmd' nocd
zinit light romkatv/powerlevel10k

# end Zinit commands

# ZSH config

# prompt config
ZLE_RPROMPT_INDENT=0

# end ZSH config

# variables
export KEYTIMEOUT=1
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# zoxide aliases
eval "$(zoxide init bash)"

# automatic cd for fff use ff to run fff
ff() {
    fff "$@"
    cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
}

# aliases
alias mirrors='sudo reflector --score 100 --fastest 25 --sort rate --save /etc/pacman.d/mirrorlist --verbose'
alias nn='nnn'
alias colorpick='grim -g "$(slurp -p)" -t ppm - | convert - -format "%[hex:s]\n" info:-'

# general use exa
alias ls='exa'                                                         # ls
alias l='exa -lbF --git'                                               # list, size, type, git
alias ll='exa -lbGF --git'                                             # long list
alias llm='exa -lbGd --git --sort=modified'                            # long list, modified date sort
alias la='exa -lbhHigSa --time-style=long-iso --git --color-scale'     # all list
alias lx='exa -lbhHigSa@ --time-style=long-iso --git --color-scale'    # all + extended list

# specialty views exa
alias lS='exa -1'                                                      # one column, just names
alias lst='exa --tree --level=2'                                       # tree

alias drop='dotdrop install'
alias dropr='sudo dotdrop --cfg=/home/{{@@ username @@}}/.config/dotdrop/config-system.yaml install'
alias dropsr='sudo -s eval $(grep -v "^#" {{@@ server_config @@}}/.env) dotdrop --cfg={{@@ server_config @@}}/config-system.yaml install'
alias drops='eval $(grep -v "^#" {{@@ server_config @@}}/.env) dotdrop --cfg={{@@ server_config @@}}/config-server.yaml install'