config:
  showdiff: true
  workdir: ~/.config/dotdrop-links
  import_variables:
    - color.yaml
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    src: config/clight.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_pulseaudio:
    src: config/pulse/daemon.conf
    dst: ~/.config/pulse/daemon.conf
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  f_gtk_settings:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  d_bin:
    link: link_children
    src: bin
    dst: ~/bin
profiles:
  shell:
    dotfiles:
      - f_zshrc
      - f_zprofile
      - f_gitconfig
      - d_bin
  gui:
    dotfiles:
      - f_xinitrc
      - f_xresources
      - d_sway
      - f_gtk_settings
      - f_alacritty
      - f_kitty
  CTOGGHA:
    include:
      - shell
  NYOGTHA:
    dotfiles:
      - f_clight
    include:
      - shell
      - gui
  AZATHOTH:
    dotfiles:
      - f_pulseaudio
    include:
      - shell
      - gui
