config:
  showdiff: false
  workdir: ~/.config/dotdrop-links
variables:
  color_fg: "f5f5f5"
  color_bg: "080808"
  color_00: "080808"
  color_08: "080808"
  color_01: "ff0000"
  color_09: "ff0000"
  color_02: "33ff00"
  color_10: "33ff00"
  color_03: "ff0099"
  color_11: "ff0099"
  color_04: "0066ff"
  color_12: "0066ff"
  color_05: "cc00ff"
  color_13: "cc00ff"
  color_06: "00ffff"
  color_14: "00ffff"
  color_07: "0d0d0d"
  color_15: "f5f5f5"
  color_black: "{{@@ color_00 @@}}"
  color_red: "{{@@ color_01 @@}}"
  color_green: "{{@@ color_02 @@}}"
  color_yellow: "{{@@ color_03 @@}}"
  color_blue: "{{@@ color_04 @@}}"
  color_magenta: "{{@@ color_05 @@}}"
  color_cyan: "{{@@ color_06 @@}}"
  color_white: "{{@@ color_07 @@}}"
  color_black_bright: "{{@@ color_08 @@}}"
  color_red_bright: "{{@@ color_09 @@}}"
  color_green_bright: "{{@@ color_10 @@}}"
  color_yellow_bright: "{{@@ color_11 @@}}"
  color_blue_bright: "{{@@ color_12 @@}}"
  color_magenta_bright: "{{@@ color_13 @@}}"
  color_cyan_bright: "{{@@ color_14 @@}}"
  color_white_bright: "{{@@ color_15 @@}}"
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    src: config/clight.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_pulseaudio:
    src: config/pulse/daemon.conf
    dst: ~/.config/pulse/daemon.conf
profiles:
  CTOGGHA:
    dotfiles:
      - f_zshrc
      - f_gitconfig
  NYOGTHA:
    dotfiles:
      - f_zshrc
      - f_xinitrc
      - f_gitconfig
      - f_clight
      - f_alacritty
      - f_xresources
  AZATHOTH:
    dotfiles:
      - f_zshrc
      - f_xinitrc
      - f_gitconfig
      - f_alacritty
      - f_xresources
      - f_kitty
      - f_pulseaudio
