config:
variables:
  config_dir: /srv/config
  data_dir: /srv/data
  timezone: Australia/Melbourne
dotfiles:
  f_docker:
    dst: "{{@@ config_dir @@}}/docker-compose.yml"
    src: server/docker-compose.yml
profiles:
  CTOGGHA:
    dotfiles:
      - f_docker
