config:
  showdiff: true
  import_variables:
    - config-server.yaml
dotfiles:
  f_touchpad:
    src: etc/X11/touchpad.conf
    dst: /etc/X11/xorg.conf.d/30-touchpad.conf
  f_issue:
    src: etc/issue
    dst: /etc/issue
  f_logind:
    src: etc/systemd/logind.conf
    dst: /etc/systemd/logind.conf
profiles:
  CTOGGHA:
    dotfiles:
      - f_issue
  NYOGTHA:
    dotfiles:
      - f_issue
      - f_logind
  AZATHOTH:
    dotfiles:
      - f_issue
      - f_logind
