# Macros
[macros.install-official]
	prefix = ["sudo", "pacman", "-S", "--noconfirm"]

[macros.install-aur]
	#todo write script to auto install pacaur
	prefix = ["pacaur", "-y", "--noconfirm"]

[macros.clone]
	deps = ["git"]
	prefix = ["git", "clone"]

[macros.enable]
	prefix = ["sudo", "systemctl", "enable"]

# Install
[tasks.fonts]
		cmds = [
			["@install-official", "adobe-source-code-pro-fonts"],
			["@install-aur", "nerd-fonts-git"],
		]

[tasks.git]
	cmds = [["@install-official", "git"]]
	links = [[".gitconfig"]]

[tasks.hyper]
	cmds = [["@install-aur", "hyper"]]
	links = [
		[".hyper.js"],
		[".hyper_plugins/local"],
	]

[tasks.emacs]
	cmds = [
		["@install-official", "emacs"],
		["@clone", "https://github.com/syl20bnr/spacemacs", ".emacs.d"],
	]

[tasks.neovim]
	cmds = [
		["@install-official", "neovim", "python-neovim"],
		["@install-aur", "neovim-drop-in"],
		["$HM_SRC/bin/spacevim_install.sh", "install", "neovim"],
	]
	links = [[".SpaceVim.d"]]

[tasks.zsh]
	cmds = [
		["@install-official", "zsh"],
		["@install-aur", "zplug", "cope-git"],
		["chsh", "-s", "/usr/bin/zsh"],
	]
	links = [[".zshrc"]]

[tasks.default]
	deps = ["zsh", "git", "hyper", "emacs", "neovim", "fonts"]
