config:
  showdiff: true
dotfiles:
  d_usr_bin:
    link: link_children
    src: usr/local/bin
    dst: /usr/local/bin
  d_greetd:
    src: etc/greetd
    dst: /etc/greetd
  d_pulseaudio:
    link: link_children
    src: etc/pulse
    dst: /etc/pulse
  f_touchpad:
    src: etc/X11/touchpad.conf
    dst: /etc/X11/xorg.conf.d/30-touchpad.conf
  f_issue:
    src: etc/issue
    dst: /etc/issue
  f_logind:
    src: etc/systemd/logind.conf
    dst: /etc/systemd/logind.conf
  f_docker:
    src: etc/docker/daemon.json
    dst: /etc/docker/daemon.json
  f_login:
    src: etc/pam.d/login
    dst: /etc/pam.d/login
profiles:
  AZATHOTH:
    dotfiles:
      - d_usr_bin
      - d_pulseaudio
      - f_issue
      - f_docker
      - f_login
  NYOGTHA:
    dotfiles:
      - d_usr_bin
      - f_issue
      - f_docker
      - f_login
  HASTUR:
    dotfiles:
      - f_issue
  CTOGGHA:
    dotfiles:
      - f_issue
  SHOGGOTH:
    dotfiles:
      - f_issue
  VULTHOOM:
    dotfiles:
      - f_issue
