# Macros
[macros.install-official]
	prefix = ["sudo", "pacman", "-S", "--noconfirm"]

[macros.install-official-deps]
	prefix = ["sudo", "pacman", "-S", "--asdeps", "--noconfirm"]

[macros.install-aur]
	#todo write script to auto install pacaur
	prefix = ["pacaur", "-y", "--noconfirm"]

[macros.install-aur-deps]
	prefix = ["pacaur", "-y", "--asdeps", "--noconfirm"]

[macros.clone]
	deps = ["git"]
	prefix = ["git", "clone"]

[macros.enable]
	prefix = ["sudo", "systemctl", "enable"]

# Install
[tasks.fonts]
	cmds = [
		["@install-official", "adobe-source-code-pro-fonts"],
		["@install-aur", "ttf-iosevka", "ttf-iosevka-term", "ttf-material-design-icons-git"],
	]

[tasks.git]
	cmds = [["@install-official", "git"]]
	links = [[".gitconfig"]]

[tasks.hyper]
	cmds = [["@install-aur", "hyper"]]
	links = [
		[".hyper.js"],
		[".hyper_plugins/local"],
	]

[tasks.emacs]
	cmds = [
		["@install-official", "emacs"],
		["@clone", "https://github.com/syl20bnr/spacemacs", ".emacs.d"],
	]

[tasks.neovim]
	cmds = [
		["@install-official", "neovim", "python-neovim"],
		["@install-aur", "neovim-drop-in"],
		["$HM_SRC/bin/spacevim_install.sh", "install", "neovim"],
	]
	links = [[".SpaceVim.d"]]

[tasks.zsh]
	cmds = [
		["@install-official", "zsh"],
		["@install-aur", "zplug", "cope-git"],
		["chsh", "-s", "/usr/bin/zsh"],
	]
	links = [[".zshrc"]]

[tasks.i3]
	cmds = [
		["@install-official", "nitrogen"],
		["@install-aur-deps", "i3lock-color-git", "scrot"],
		["@install-aur", "i3-gaps-next-git", "i3lock-fancy", "rofi-git"]
	]
	links = [
		[".config/i3"],
		[".config/i3blocks"],
		[".config/compton.conf"],
		[".Xresources"]
	]

[tasks.bin]
	links = [["bin/colortest"]]

[tasks.default]
	deps = ["zsh", "git", "i3", "bin", "hyper", "emacs", "neovim", "fonts"]
