config:
  showdiff: true
dotfiles:
  d_pulseaudio:
    link: link_children
    src: etc/pulse
    dst: /etc/pulse
  f_touchpad:
    src: etc/X11/touchpad.conf
    dst: /etc/X11/xorg.conf.d/30-touchpad.conf
  f_issue:
    src: etc/issue
    dst: /etc/issue
  f_logind:
    src: etc/systemd/logind.conf
    dst: /etc/systemd/logind.conf
profiles:
  CTOGGHA:
    dotfiles:
      - f_issue
  NYOGTHA:
    dotfiles:
      - f_issue
  AZATHOTH:
    dotfiles:
      - d_pulseaudio
      - f_issue
  SHOGGOTH:
    dotfiles:
      - f_issue
  VULTHOOM:
    dotfiles:
      - f_issue
  HASTUR:
    dotfiles:
      - f_issue
