# Macros
[macros.install-official]
	prefix = ["sudo", "pacman", "-S", "--noconfirm"]

[macros.install-aur]
	#todo write script in auto install pacaur
	prefix = ["pacaur", "-y", "--noconfirm"]

[macros.clone]
	deps = ["git"]
	prefix = ["git", "clone"]

[macros.enable]
	prefix = ["sudo", "systemctl", "enable"]

# Install
[tasks.git]
	cmds = [["@install-official", "git"]]
	links = [[".gitconfig"]]

[tasks.hyper]
	cmds = [["@install-aur", "hyper"]]
	links = [
		[".hyper.js"],
		[".hyper_plugins/local"],
	]

[tasks.emacs]
	cmds = [
		["@install-official", "emacs"],
		["@clone", "https://github.com/syl20bnr/spacemacs", ".emacs.d"],
	]

[tasks.default]
	deps = ["git", "hyper", "emacs"]
