actions:
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    link: true
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    link: true
    src: config/clight.conf
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    link: true
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    link: true
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc
profiles:
  CTOGGHA:
    dotfiles:
      - f_zshrc
      - f_gitconfig
  NYOGTHA:
    dotfiles:
      - f_zshrc
      - f_xinitrc
      - f_gitconfig
      - f_clight
      - f_alacritty
