actions:
  spacevim: test -e ~/.SpaceVim || curl -sLf https://spacevim.org/install.sh | bash
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_polybar:
    dst: ~/.config/polybar
    link: true
    src: config/polybar
  f_i3_config:
    dst: ~/.config/i3/config
    link: true
    src: config/i3/config
  f_vim_init:
    actions:
    - spacevim
    dst: ~/.SpaceVim.d/init.toml
    link: true
    src: SpaceVim.d/init.toml
  f_xinitrc:
    dst: ~/.xinitrc
    link: true
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc
profiles:
  NYOGTHA:
    dotfiles:
    - f_zshrc
    - f_xinitrc
    - f_i3_config
    - f_vim_init
    - d_polybar
