actions:
  pre:
    spacemacs:
      test -e ~/.config/spacemacs || git clone https://github.com/syl20bnr/spacemacs
      ~/.config/spacemacs
    doom: test -e ~/.doom || git clone https://github.com/hlissner/doom-emacs ~/.doom
    chemacs: test -e ~/.config/chemacs || git clone https://github.com/plexus/chemacs.git ~/.config/chemacs
  post:
    emacsserver: systemctl --user enable --now emacs
    chemacs_install: test -e ~/.emacs || ~/.config/chemacs/install.sh
config:
  workdir: ~/.config/dotdrop-links
  import_variables:
    - color.yaml
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    src: config/clight.conf
  f_swaynag:
    dst: ~/.config/swaynag/config
    src: config/swaynag.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    link: link
    dst: ~/.zshrc
    src: zshrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_pulseaudio:
    src: config/pulse/daemon.conf
    dst: ~/.config/pulse/daemon.conf
  f_zprofile:
    src: zshenv
    dst: ~/.zshenv
  d_redshift:
    dst: ~/.config/redshift
    src: config/redshift
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_gtk_settings:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  d_bin:
    link: link_children
    src: bin
    dst: ~/bin
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_autostart:
    link: link_children
    src: config/autostart
    dst: ~/.config/autostart
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_spacevim.d:
    link: link
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
  f_p10k:
    link: link
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_spacemacs.d:
    link: link
    src: spacemacs.d
    dst: ~/.spacemacs.d
    actions:
      - spacemacs
      - emacsserver
  d_doom.d:
    link: link
    src: doom.d
    dst: ~/.doom.d
    actions:
      - doom
  f_emacs-profiles.el:
    link: link
    src: emacs-profiles.el
    dst: ~/.emacs-profiles.el
    actions:
      - chemacs
      - chemacs_install
profiles:
  emacs:
    dotfiles:
      - d_spacemacs.d
      - d_doom.d
      - f_emacs-profiles.el
  shell:
    dotfiles:
      - d_bin
      - f_gitconfig
      - f_p10k
      - f_zprofile
      - f_zshrc
  applications:
    dotfiles:
      - d_spacevim.d
      - f_alacritty
      - f_kitty
    include:
      - emacs
  gui_wayland:
    dotfiles:
      - d_redshift
      - d_sway
      - d_waybar
      - d_wofi
      - f_gtk_settings
      - f_swaynag
      - f_xresources
  gui_x11:
    dotfiles:
      - d_autostart
      - d_i3
      - d_rofi
      - f_gtk_settings
      - f_xinitrc
      - f_xresources
  CTOGGHA:
    include:
      - shell
  NYOGTHA:
    include:
      - applications
      - gui_wayland
      - shell
  AZATHOTH:
    dotfiles:
      - f_pulseaudio
    include:
      - applications
      - gui_wayland
      - shell
