config:
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    link: link
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    link: link
    src: config/clight.conf
  f_gitconfig:
    dst: ~/.gitconfig
    link: link
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    link: link
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    link: link
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    link: link
    src: zshrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    link: link
profiles:
  CTOGGHA:
    dotfiles:
      - f_zshrc
      - f_gitconfig
  NYOGTHA:
    dotfiles:
      - f_zshrc
      - f_xinitrc
      - f_gitconfig
      - f_clight
      - f_alacritty
      - f_xresources
  AZATHOTH:
    dotfiles:
      - f_zshrc
      - f_xinitrc
      - f_gitconfig
      - f_alacritty
      - f_xresources
