actions:
  pre:
    spacemacs:
      test -e ~/.emacs.d || git clone https://github.com/syl20bnr/spacemacs
      ~/.emacs.d
  post:
    emacsserver: systemctl --user enable --now emacs
config:
  workdir: ~/.config/dotdrop-links
  import_variables:
    - color.yaml
dotfiles:
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_clight:
    dst: ~/.config/clight.conf
    src: config/clight.conf
  f_swaynag:
    dst: ~/.config/swaynag/config
    src: config/swaynag.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_kitty:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_pulseaudio:
    src: config/pulse/daemon.conf
    dst: ~/.config/pulse/daemon.conf
  f_zprofile:
    src: zshenv
    dst: ~/.zshenv
  d_redshift:
    dst: ~/.config/redshift
    src: config/redshift
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_gtk_settings:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  d_bin:
    link: link_children
    src: bin
    dst: ~/bin
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_applications:
    link: link_children
    src: local/share/applications
    dst: ~/.local/share/applications
  d_autostart:
    link: link_children
    src: config/autostart
    dst: ~/.config/autostart
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_spacevim.d:
    link: link
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
  f_spacemacs:
    link: link
    src: spacemacs
    dst: ~/.spacemacs
    actions:
      - spacemacs
      - emacsserver
  f_p10k:
    link: link
    src: p10k.zsh
    dst: ~/.p10k.zsh
profiles:
  shell:
    dotfiles:
      - f_p10k
      - f_zshrc
      - f_zprofile
      - f_gitconfig
      - d_bin
  applications:
    dotfiles:
      - f_kitty
      - f_alacritty
      - f_spacemacs
      - d_spacevim.d
  gui_wayland:
    dotfiles:
      - f_gtk_settings
      - f_xresources
      - f_swaynag
      - d_sway
      - d_waybar
      - d_wofi
      - d_redshift
    include:
      - shell
      - applications
  gui_x11:
    dotfiles:
      - d_i3
      - f_xinitrc
      - f_xresources
      - f_gtk_settings
      - d_autostart
      - d_rofi
    include:
      - shell
      - applications
  CTOGGHA:
    include:
      - shell
  NYOGTHA:
    include:
      - gui_wayland
  AZATHOTH:
    dotfiles:
      - f_pulseaudio
    include:
      - gui_wayland
