global:
  scrape_interval: 1m
  evaluation_interval: 1m
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "localhost"
    static_configs:
      - targets: ["localhost:9100"]
