version: "3.7"
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptcert.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencryptcert.acme.dnschallenge.provider=dnsimple"
      - "--certificatesresolvers.letsencryptcert.acme.email={{@@ env['EMAIL'] @@}}"
      - "--certificatesresolvers.letsencryptcert.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    environment:
      - "DNSIMPLE_OAUTH_TOKEN={{@@ env['DNSIMPLE_TOKEN'] @@}}"
      - "DNSIMPLE_BASE_URL={{@@ env['DNSIMPLE_BASE_URL'] @@}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{@@ config_dir @@}}/letsencrypt:/letsencrypt"
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - "{{@@ config_dir @@}}/heimdall:/config"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencryptcert"
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - "{{@@ config_dir @@}}/smokeping:/config"
      - "{{@@ data_dir @@}}/containers/smokeping:/data"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.smokeping.entrypoints=websecure"
      - "traefik.http.routers.smokeping.tls.certresolver=letsencryptcert"
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
      - CONTEXT_PATH="airsonic.{{@@ env['DOMAIN'] @@}}"
    volumes:
      - "{{@@ config_dir @@}}/airsonic:/config"
      - "{{@@ data_dir @@}}/music:/music"
      - "{{@@ data_dir @@}}/containers/airsonic/playlists:/playlists"
      - "{{@@ data_dir @@}}/podcasts:/podcasts"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.airsonic.entrypoints=websecure"
      - "traefik.http.routers.airsonic.tls.certresolver=letsencryptcert"
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - "{{@@ config_dir @@}}/freshrss:/config"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`freshrss.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.tls.certresolver=letsencryptcert"
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - "{{@@ config_dir @@}}/grocy:/config"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.rule=Host(`grocy.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.grocy.entrypoints=websecure"
      - "traefik.http.routers.grocy.tls.certresolver=letsencryptcert"
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - "{{@@ data_dir @@}}/books:/books"
      - "{{@@ config_dir @@}}/calibre-web:/config"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre-web.{{@@ env['DOMAIN'] @@}}`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls.certresolver=letsencryptcert"
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    init: true
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      # rutorrent ports
      - 9999:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    environment:
      - VPNSP=pia
      - USER={{@@ env['PIA_USER'] @@}}
      - TZ={{@@ timezone @@}}
      - EXTRA_SUBNETS=10.10.10.0/24
      # PIA only
      - REGION=Singapore
      - PASSWORD={{@@ env['PIA_PASS'] @@}}
      - ENCRYPTION=strong
    restart: always
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    network_mode: "service:pia"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "{{@@ config_dir @@}}/rutorrent:/config"
      - "{{@@ data_dir @@}}/containers/rutorrent:/downloads"
    restart: unless-stopped
