version: "3.7"
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - {{@@ config_dir @@}}/heimdall:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.127.0.0.1`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - {{@@ config_dir @@}}/smokeping:/config
      - {{@@ data_dir @@}}/containers/smokeping:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.127.0.0.1`)"
      - "traefik.http.routers.smokeping.entrypoints=web"
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - {{@@ config_dir @@}}/freshrss:/config
    ports:
      - 4545:80
    restart: unless-stopped
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{@@ timezone @@}}
    volumes:
      - {{@@ config_dir @@}}/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    init: true
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      # rutorrent ports
      - 9999:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    environment:
      - VPNSP=pia
      - USER={{@@ env['PIA_USER'] @@}}
      - TZ={{@@ timezone @@}}
      - EXTRA_SUBNETS=10.10.10.0/24
      # PIA only
      - REGION=Singapore
      - PASSWORD={{@@ env['PIA_PASS'] @@}}
      - ENCRYPTION=strong
    restart: always
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    network_mode: "service:pia"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - {{@@ config_dir @@}}/rutorrent:/config
      - {{@@ data_dir @@}}/containers/rutorrent:/downloads
    restart: unless-stopped
