#!/bin/sh

# Source scripts in xinit.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Change caps lock to an escape key
setxkbmap -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps

# Load xresources
[[ -f ~/.xresources ]] && xrdb -merge ~/.xresources

# Start window manager
exec ~/bin/startwm
