# {{@@ header() @@}}
# Font configuration (changes require restart)
#
# Important font attributes like antialiasing, subpixel aa, and hinting can be
# controlled through fontconfig. Specifically, the following attributes should
# have an effect:
#   - hintstyle
#   - antialias
#   - lcdfilter
#   - rgba
#
# For instance, if you wish to disable subpixel antialiasing, you might set the
# rgba property to `none`. If you wish to completely disable antialiasing, you
# can set antialias to `false`.
#
# Please see these resources for more information on how to use fontconfig:
#   - https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
#   - file:///usr/share/doc/fontconfig/fontconfig-user.html
font:
  # Normal (roman) font face
  normal:
    family: Cozette

colors:
  # Default colors
  primary:
    background: "0x{{@@ color_bg @@}}"
    foreground: "0x{{@@ color_fg @@}}"

  # Normal colors
  normal:
    black: "0x{{@@ color_00 @@}}"
    red: "0x{{@@ color_01 @@}}"
    green: "0x{{@@ color_02 @@}}"
    yellow: "0x{{@@ color_03 @@}}"
    blue: "0x{{@@ color_04 @@}}"
    magenta: "0x{{@@ color_05 @@}}"
    cyan: "0x{{@@ color_06 @@}}"
    white: "0x{{@@ color_07 @@}}"

  # Bright colors
  bright:
    black: "0x{{@@ color_08 @@}}"
    red: "0x{{@@ color_09 @@}}"
    green: "0x{{@@ color_10 @@}}"
    yellow: "0x{{@@ color_11 @@}}"
    blue: "0x{{@@ color_12 @@}}"
    magenta: "0x{{@@ color_13 @@}}"
    cyan: "0x{{@@ color_14 @@}}"
    white: "0x{{@@ color_15 @@}}"
