# Font configuration (changes require restart)
#
# Important font attributes like antialiasing, subpixel aa, and hinting can be
# controlled through fontconfig. Specifically, the following attributes should
# have an effect:
#   - hintstyle
#   - antialias
#   - lcdfilter
#   - rgba
#
# For instance, if you wish to disable subpixel antialiasing, you might set the
# rgba property to `none`. If you wish to completely disable antialiasing, you
# can set antialias to `false`.
#
# Please see these resources for more information on how to use fontconfig:
#   - https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
#   - file:///usr/share/doc/fontconfig/fontconfig-user.html
font:
  # Normal (roman) font face
  normal:
    family: Iosevka Term
    style: Regular

  # Bold font face
  bold:
    family: Iosevka Term
    style: Bold

  # Italic font face
  italic:
    family: Iosevka Term
    style: Italic

  # Point size
  size: 14.0

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Values for `animation`:
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
#
# Specifying a `duration` of `0` will disable the visual bell.
visual_bell:
  animation: EaseOutExpo
  duration: 0

colors:
  # Default colors
  primary:
    background: "0x080808"
    foreground: "0xf5f5f5"

  # Normal colors
  normal:
    black: "0x080808"
    red: "0xff0000"
    green: "0x33ff00"
    yellow: "0xff0099"
    blue: "0x0066ff"
    magenta: "0xcc00ff"
    cyan: "0x00ffff"
    white: "0xd0d0d0"

  # Bright colors
  bright:
    black: "0x808080"
    red: "0xff0000"
    green: "0x33ff00"
    yellow: "0xff0099"
    blue: "0x0066ff"
    magenta: "0xcc00ff"
    cyan: "0x00ffff"
    white: "0xf5f5f5"
