# {{@@ header() @@}}
# Font configuration (changes require restart)
#
# Important font attributes like antialiasing, subpixel aa, and hinting can be
# controlled through fontconfig. Specifically, the following attributes should
# have an effect:
#   - hintstyle
#   - antialias
#   - lcdfilter
#   - rgba
#
# For instance, if you wish to disable subpixel antialiasing, you might set the
# rgba property to `none`. If you wish to completely disable antialiasing, you
# can set antialias to `false`.
#
# Please see these resources for more information on how to use fontconfig:
#   - https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
#   - file:///usr/share/doc/fontconfig/fontconfig-user.html
font:
  # Normal (roman) font face
  normal:
    family: Cozette
    antialias: false

  # Bold font face
  bold:
    style: Regular

  # Italic font face
  italic:
    style: Regular

  # Bold italic font face
  bold_italic:
    style: Regular

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true


colors:
  # Default colors
  primary:
    background: "#{{@@ color_bg @@}}"
    foreground: "#{{@@ color_fg @@}}"

  # Normal colors
  normal:
    black: "#{{@@ color_black @@}}"
    red: "#{{@@ color_red @@}}"
    green: "#{{@@ color_green @@}}"
    yellow: "#{{@@ color_yellow @@}}"
    blue: "#{{@@ color_blue @@}}"
    magenta: "#{{@@ color_magenta @@}}"
    cyan: "#{{@@ color_cyan @@}}"
    white: "#{{@@ color_white @@}}"

  # Bright colors
  bright:
    black: "#{{@@ color_black_bright @@}}"
    red: "#{{@@ color_red_bright @@}}"
    green: "#{{@@ color_green_bright @@}}"
    yellow: "#{{@@ color_yellow_bright @@}}"
    blue: "#{{@@ color_blue_bright @@}}"
    magenta: "#{{@@ color_magenta_bright @@}}"
    cyan: "#{{@@ color_cyan_bright @@}}"
    white: "#{{@@ color_white_bright @@}}"
