#!/bin/bash

if [[ -d ~/.emacs.d ]]; then
    echo "already installed"
else
    echo "Starting install script"
    sh <(curl https://github.com/bbatsov/prelude/raw/master/utils/installer.sh -L)
fi

exit $?
